functionsDirectory = "C:\\Users\\fikri.nabil\\Desktop\\bnsV revamp\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\fikri.nabil\\Desktop\\bnsV revamp"
publishOrigin = "config"
functions = "C:\\Users\\fikri.nabil\\Desktop\\bnsV revamp\\netlify\\functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[dev]
edge_functions = []

[functions]

  [functions."*"]
  included_files = [
    "netlify/functions/**"
  ]
  node_bundler = "esbuild"